baseURL: "https://marcoyxz.github.io/"
languageCode: "en-us"
title: "marco's tech blog"
theme: "PaperMod"
author: 'Marco Zhan'
keywords: ['personal', 'tech', 'blog']
ShowReadingTime: true
ShowCodeCopyButtons: true
comments: true
publishDir: "docs"
disqusShortname: https-marcoyxz-github-io

params:
  defaultTheme: auto
  homeInfoParams:
    Content: Disorganised tech blog about whatever interesting stuff I encountered

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/marcoYxz"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/marcozhan/"
