baseURL: "https://marcoyxz.github.io/"
languageCode: "en-au"
title: "marco's tech blog"
theme: "PaperMod"
author: 'Marco Zhan'
disqusShortname: https-marcoyxz-github-io
publishDir: "docs"

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  comments: true
  keywords: ['personal', 'tech', 'blog']
  homeInfoParams:
    Content: Disorganised tech blog about whatever interesting stuff I encountered

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/marcoYxz"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/marcozhan/"
